### ISSUE TITLE
Fails to build under Linux

### ISSUE THREAD

**Issue by h6899** [EAVi/Ninja#6]
make -j4
g++ -std=c++11 -o Ninja Algorithms.o Cannon.o Cutscene.o Demon.o Enemy.o Game.o LAudio.o Level.o LevelID.o LTexture.o main.o Menu.o Player.o Robot.o TextWriter.o Timer.o UIDrawer.o Zone.o -lSDL2 -lSDL2_image -lSDL2_mixer 
/usr/bin/ld: Game.o: in function `Game::loadAssets()':
Game.cpp:(.text+0x1fe5): undefined reference to `Samurai::Samurai()'
/usr/bin/ld: Game.cpp:(.text+0x20ba): undefined reference to `Samurai::setTexture(LTexture*)'
/usr/bin/ld: Game.cpp:(.text+0x2704): undefined reference to `Samurai::~Samurai()'
/usr/bin/ld: Game.cpp:(.text+0x31e9): undefined reference to `Samurai::~Samurai()'
/usr/bin/ld: Level.o: in function `Level::addEnemy(unsigned char, unsigned char, unsigned char)':
Level.cpp:(.text+0xdb2): undefined reference to `Samurai::Samurai(unsigned char, unsigned char, bool, Level*)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:17: Ninja] Error 1

**Comment by EAVi** [comment]
Whoops, I haven't tested my latest update on Linux yet, I'll be working on it.

**Comment by EAVi** [comment]
Thank you for the report. It is fixed and runs on Ubuntu
